/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __com_example_jnicallbcak_WorkingJni__
#define __com_example_jnicallbcak_WorkingJni__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_com_example_jnicallbcak_WorkingJni_myJni (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __com_example_jnicallbcak_WorkingJni__ */
